// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: permissions.proto

package permissions

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Permission int32

const (
	Permission_None             Permission = 0
	Permission_Read             Permission = 1
	Permission_R                Permission = 1
	Permission_Write            Permission = 2
	Permission_W                Permission = 2
	Permission_ReadWrite        Permission = 3
	Permission_RW               Permission = 3
	Permission_Execute          Permission = 4
	Permission_E                Permission = 4
	Permission_ReadExecute      Permission = 5
	Permission_RE               Permission = 5
	Permission_WriteExecute     Permission = 6
	Permission_WE               Permission = 6
	Permission_ReadWriteExecute Permission = 7
	Permission_RWE              Permission = 7
	Permission_All              Permission = 7
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "None",
		1: "Read",
		// Duplicate value: 1: "R",
		2: "Write",
		// Duplicate value: 2: "W",
		3: "ReadWrite",
		// Duplicate value: 3: "RW",
		4: "Execute",
		// Duplicate value: 4: "E",
		5: "ReadExecute",
		// Duplicate value: 5: "RE",
		6: "WriteExecute",
		// Duplicate value: 6: "WE",
		7: "ReadWriteExecute",
		// Duplicate value: 7: "RWE",
		// Duplicate value: 7: "All",
	}
	Permission_value = map[string]int32{
		"None":             0,
		"Read":             1,
		"R":                1,
		"Write":            2,
		"W":                2,
		"ReadWrite":        3,
		"RW":               3,
		"Execute":          4,
		"E":                4,
		"ReadExecute":      5,
		"RE":               5,
		"WriteExecute":     6,
		"WE":               6,
		"ReadWriteExecute": 7,
		"RWE":              7,
		"All":              7,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_permissions_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_permissions_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{0}
}

type Permissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  Permission `protobuf:"varint,1,opt,name=user,proto3,enum=permissions.Permission" json:"user,omitempty"`
	Group Permission `protobuf:"varint,2,opt,name=group,proto3,enum=permissions.Permission" json:"group,omitempty"`
	Other Permission `protobuf:"varint,3,opt,name=other,proto3,enum=permissions.Permission" json:"other,omitempty"`
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permissions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *Permissions) GetUser() Permission {
	if x != nil {
		return x.User
	}
	return Permission_None
}

func (x *Permissions) GetGroup() Permission {
	if x != nil {
		return x.Group
	}
	return Permission_None
}

func (x *Permissions) GetOther() Permission {
	if x != nil {
		return x.Other
	}
	return Permission_None
}

var File_permissions_proto protoreflect.FileDescriptor

var file_permissions_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x01, 0x0a, 0x0b, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x37, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02,
	0x10, 0x01, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x37, 0x0a, 0x05, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02, 0x10, 0x01, 0x52, 0x05, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x2a, 0xc3, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x10, 0x02, 0x12, 0x05, 0x0a, 0x01, 0x57, 0x10, 0x02, 0x12, 0x0d,
	0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x10, 0x03, 0x12, 0x06, 0x0a,
	0x02, 0x52, 0x57, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x10, 0x04, 0x12, 0x05, 0x0a, 0x01, 0x45, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x65, 0x61,
	0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x52, 0x45,
	0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02, 0x57, 0x45, 0x10, 0x06, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x65, 0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x10, 0x07, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x57, 0x45, 0x10, 0x07, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x6c, 0x6c, 0x10, 0x07, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6c, 0x65, 0x73, 0x7a, 0x69, 0x6c, 0x6d, 0x2f,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_permissions_proto_rawDescOnce sync.Once
	file_permissions_proto_rawDescData = file_permissions_proto_rawDesc
)

func file_permissions_proto_rawDescGZIP() []byte {
	file_permissions_proto_rawDescOnce.Do(func() {
		file_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_permissions_proto_rawDescData)
	})
	return file_permissions_proto_rawDescData
}

var file_permissions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_permissions_proto_goTypes = []interface{}{
	(Permission)(0),     // 0: permissions.Permission
	(*Permissions)(nil), // 1: permissions.Permissions
}
var file_permissions_proto_depIdxs = []int32{
	0, // 0: permissions.Permissions.user:type_name -> permissions.Permission
	0, // 1: permissions.Permissions.group:type_name -> permissions.Permission
	0, // 2: permissions.Permissions.other:type_name -> permissions.Permission
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_permissions_proto_init() }
func file_permissions_proto_init() {
	if File_permissions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_permissions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_permissions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permissions_proto_goTypes,
		DependencyIndexes: file_permissions_proto_depIdxs,
		EnumInfos:         file_permissions_proto_enumTypes,
		MessageInfos:      file_permissions_proto_msgTypes,
	}.Build()
	File_permissions_proto = out.File
	file_permissions_proto_rawDesc = nil
	file_permissions_proto_goTypes = nil
	file_permissions_proto_depIdxs = nil
}
