// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: permissions.proto

package permissions

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _permissions_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Permissions with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Permissions) Validate() error {
	if m == nil {
		return nil
	}

	if _, ok := Permission_name[int32(m.GetUser())]; !ok {
		return PermissionsValidationError{
			field:  "User",
			reason: "value must be one of the defined enum values",
		}
	}

	if _, ok := Permission_name[int32(m.GetGroup())]; !ok {
		return PermissionsValidationError{
			field:  "Group",
			reason: "value must be one of the defined enum values",
		}
	}

	if _, ok := Permission_name[int32(m.GetOther())]; !ok {
		return PermissionsValidationError{
			field:  "Other",
			reason: "value must be one of the defined enum values",
		}
	}

	return nil
}

// PermissionsValidationError is the validation error returned by
// Permissions.Validate if the designated constraints aren't met.
type PermissionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionsValidationError) ErrorName() string { return "PermissionsValidationError" }

// Error satisfies the builtin error interface
func (e PermissionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionsValidationError{}
